### ISSUE TITLE
Clock Source (HSE or HSI)

### ISSUE THREAD

**Issue by gxdeange** [grblHAL/STM32F7xx#7]
Hi terjeio,

Can I please ask if the firmware will use the HSE or HSI as the clock source.

I assume that because this is a Nucleo board that it will use the HSI? 

Regards
George

**Comment by terjeio** [comment]
It uses [HSE](https://github.com/grblHAL/STM32F7xx/blob/d14877250d83f84ddc5abb3bf3086de354d99969/Src/main.c#L45) sourced from ST-LINK. See section 6.8.1 in the Nucleo 144 user manual (UM1974).

**Comment by gxdeange** [comment]
Can the firmware be configured for HSI (similar to how it is done for the
446 Nucleo)?

Regards George

**Comment by terjeio** [comment]
Yes, IMO the best way is to create a new project to tweak the settings and then copy the clock setup code to the driver.

**Comment by gxdeange** [comment]
Ok.

Would you be able to advise which driver file?

I can look at the HSI clock settings and adjust for maximum performance.

Cheers and have a great day
George

**Comment by terjeio** [comment]
> Would you be able to advise which driver file?

[main.c](https://github.com/grblHAL/STM32F7xx/blob/d14877250d83f84ddc5abb3bf3086de354d99969/Src/main.c#L38-L84)

Have a great day too!

**Comment by gxdeange** [comment]
Awesome.

Cheers George

**Comment by gxdeange** [comment]
All Good
