### ISSUE TITLE
That's cool, terjeio, thanks to your efforts grbl supports up to 8 axes? (sorry, I can't count), so I have an idea

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F7xx#9]
According to your project STM32F756ZGT6 made for pure motor control 8-axis control board, support USB, serial port, Ethernet, it feels very interesting

**Comment by terjeio** [comment]
Yes, and if another control language is to be used that can replace the gcode parser - ref the [HPGL plugin](https://github.com/grblHAL/Templates/tree/master/my_plugin/hpgl) that does just that.
